/**
 * Off Script Versions — B-side rewrites for every Ready Bank format.
 *
 * Each entry maps to a QuickDropTemplate by id and adds the deeper
 * "social script / script break" angle that makes content feel like
 * AZ Off Script instead of generic TikTok prompts.
 *
 * The A version (current) stays untouched. The B version sits beside it.
 */

export interface OffScriptVersion {
  /** Matches QuickDropTemplate.id */
  templateId: string;
  /** B-side title */
  scriptTitle: string;
  /** B-side description */
  scriptDescription: string;
  /** The social script being broken (the expected rule) */
  socialScript: string;
  /** The break — how AZ Off Script flips it */
  scriptBreak: string;
  /** Question that mirrors the audience's own experience */
  audienceMirror: string;
  /** B-side caption starter */
  scriptCaptionStarter: string;
  /** Prompt examples for the B version */
  promptExamples: string[];
  /** Script-layer tags for filtering */
  scriptTags: string[];
  /** Depth level note */
  depthLevel: string;
}

export const SCRIPT_LAYER_FILTERS = [
  "Script Check",
  "Script Break",
  "Polite Line",
  "Family Script",
  "Mom Script",
  "Friendship Script",
  "Dating Script",
  "Arizona Script",
  "Culture Script",
  "Soft Truth",
  "Funny Truth",
  "Comment Reaction",
  "No Talking Needed",
] as const;

export const OFF_SCRIPT_VERSIONS: OffScriptVersion[] = [
  {
    templateId: "first_wave_intro",
    scriptTitle: "First Wave Script Break Intro",
    scriptDescription: "Each person introduces themselves by naming the social script they are not reading anymore. Still simple, still stitched, but deeper than a basic intro.",
    socialScript: "People introduce themselves by sounding polished, agreeable, and easy to place.",
    scriptBreak: "Each woman introduces herself by what she is done pretending, shrinking, or editing.",
    audienceMirror: "Which one of these women says the thing you wish you could say?",
    scriptCaptionStarter: "Meet the First Wave. Same room. Different scripts. Nobody reads them the same.",
    promptExamples: [
      "I'm Vanessa, and I'm done making big ideas small so people feel comfortable.",
      "I'm Sholanda, and I'm done pretending I didn't peep it.",
      "I'm Ronnie, and I can be sweet without being silent.",
      "I'm Elaine, and my face usually says what my mouth doesn't.",
      "I'm Latasha, and I'm not here to give the expected answer.",
      "I'm Maria, and I'm bringing the energy before the script catches up.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "step_into_the_room",
    scriptTitle: "Step Out of the Script",
    scriptDescription: "Each person steps toward the camera and says one line that breaks a rule people act like they still have to follow.",
    socialScript: "Stay agreeable. Keep it cute. Do not make the room uncomfortable.",
    scriptBreak: "Step into frame and say the part people usually edit out.",
    audienceMirror: "What script are you done stepping into?",
    scriptCaptionStarter: "The script said one thing. The room stepped in with another.",
    promptExamples: [
      "The script says be the bigger person. I say why is it always me?",
      "The script says don't take it personal. I say stop making it personal.",
      "The script says keep the peace. I say peace for who?",
      "The script says laugh it off. I say I'm not laughing today.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "zoom_verdict",
    scriptTitle: "Zoom Out, Say the Real Part",
    scriptDescription: "Start close, zoom out, and reveal the truth underneath the polite answer.",
    socialScript: "Give the acceptable answer first.",
    scriptBreak: "Zoom out into the honest answer.",
    audienceMirror: "Did your answer change once you stopped trying to sound nice?",
    scriptCaptionStarter: "Zoom out. The polite answer was not the real one.",
    promptExamples: [
      "Close-up: It's fine. Zoom-out: It has not been fine for three months.",
      "Close-up: I understand. Zoom-out: I'm tired of understanding alone.",
      "Close-up: No worries. Zoom-out: Actually, worry.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "cover_camera",
    scriptTitle: "Cover the Script",
    scriptDescription: "Cover the camera with a hand, tumbler, purse, phone, shirt, or sunglasses, then reveal the reaction or line that breaks the script.",
    socialScript: "Hide the real reaction until you can act normal again.",
    scriptBreak: "Cover, reveal, and let the real reaction show.",
    audienceMirror: "What would your face reveal before your mouth could fix it?",
    scriptCaptionStarter: "Covered the camera. Couldn't cover the truth.",
    promptExamples: [
      "When somebody says family can say anything because they're family.",
      "When the group chat says 'be mature' but you were already too mature for too long.",
      "When he says 'I didn't think it was a big deal.'",
    ],
    scriptTags: ["Script Layer", "Script Break", "No Talking Needed"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "walk_off_answer",
    scriptTitle: "Say It and Leave the Script",
    scriptDescription: "Give one honest line, then walk out of frame like the script is no longer worth explaining.",
    socialScript: "Explain yourself until everybody feels okay.",
    scriptBreak: "Say the truth once and leave the frame.",
    audienceMirror: "What truth would you say once and stop explaining?",
    scriptCaptionStarter: "Said it once. Left the script there.",
    promptExamples: [
      "I'm not calling it peace if I'm the only one swallowing everything.",
      "Family is not a free pass.",
      "Low maintenance got me ignored.",
      "No response is also an answer.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "object_pass",
    scriptTitle: "Pass the Script",
    scriptDescription: "Pass an object around while each person reacts to the same social rule differently.",
    socialScript: "Everybody is supposed to respond the same way.",
    scriptBreak: "The same prompt hits each woman differently.",
    audienceMirror: "Which answer would you have passed back?",
    scriptCaptionStarter: "Same script passed around the room. Nobody read it the same.",
    promptExamples: [
      "Pass the tumbler: 'Be the bigger person.'",
      "Pass the phone: 'It's not that deep.'",
      "Pass the sunglasses: 'That's just how they are.'",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "chair_spin",
    scriptTitle: "Spin Into the Real Answer",
    scriptDescription: "Start turned away, spin to camera, and reveal the answer people were not expecting.",
    socialScript: "Prepare the perfect, acceptable response.",
    scriptBreak: "Spin into the answer before the script can soften it.",
    audienceMirror: "Would your first answer be polite or real?",
    scriptCaptionStarter: "Spun around before the script could stop her.",
    promptExamples: [
      "When they ask if you're over it.",
      "When someone says you changed.",
      "When the family asks why you don't come around anymore.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "face_only_reaction",
    scriptTitle: "The Face Broke Script",
    scriptDescription: "No talking. Just the face you make when the rule, excuse, or situation no longer makes sense.",
    socialScript: "Act normal even when the situation is ridiculous.",
    scriptBreak: "Let the face say what the script told you not to.",
    audienceMirror: "Did your face say it too?",
    scriptCaptionStarter: "No words. The script broke on her face.",
    promptExamples: [
      "When someone says 'just be the bigger person.'",
      "When he says 'I forgot' for the fifth time.",
      "When they call disrespect 'family being family.'",
    ],
    scriptTags: ["Script Layer", "Script Break", "No Talking Needed"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "one_line_verdict",
    scriptTitle: "One-Line Script Break",
    scriptDescription: "One sentence that says what people usually edit out.",
    socialScript: "Make the truth softer so people can handle it.",
    scriptBreak: "Say the clean, sharp version.",
    audienceMirror: "Which line did you need to hear?",
    scriptCaptionStarter: "One line. Whole script broken.",
    promptExamples: [
      "Being the strong one is not a personality. It is exhaustion.",
      "If I have to shrink to keep it, I do not want it.",
      "Not everything needs forgiveness to prove you healed.",
      "Peace that only costs me is not peace.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Soft Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "arizona_micro_moment",
    scriptTitle: "Arizona Script Check",
    scriptDescription: "A quick Arizona-specific rule, habit, or reality that people here understand immediately.",
    socialScript: "Arizona is just heat and cactus jokes.",
    scriptBreak: "Show the real local habit, mood, or survival logic.",
    audienceMirror: "Are you Arizona enough to get it?",
    scriptCaptionStarter: "Arizona script check. If you live here, you already know.",
    promptExamples: [
      "The script says summer starts in June. Arizona says try March.",
      "The script says run errands later. Arizona says before 9 a.m. or suffer.",
      "The script says cute outfit. Arizona says breathable first.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Arizona Script", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "arizona_made_me",
    scriptTitle: "Arizona Rewrote Me",
    scriptDescription: "How Arizona changed your habits, standards, patience, schedule, driving, style, or survival instincts.",
    socialScript: "A place is just where you live.",
    scriptBreak: "Arizona changed how you move.",
    audienceMirror: "What did Arizona rewrite in you?",
    scriptCaptionStarter: "Arizona rewrote the script. What did it do to you?",
    promptExamples: [
      "Arizona made me judge parking spots by shade first.",
      "Arizona made me suspicious of anything scheduled outdoors after May.",
      "Arizona made iced drinks a personality trait.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Arizona Script", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "only_arizona_understand",
    scriptTitle: "Arizona Knows the Line",
    scriptDescription: "A local moment where Arizona people instantly understand the unspoken meaning.",
    socialScript: "Everybody experiences the same thing the same way.",
    scriptBreak: "Arizona has its own version of normal.",
    audienceMirror: "If you know, you know. If you do not, you are learning.",
    scriptCaptionStarter: "Only Arizona people know what this line really means.",
    promptExamples: [
      "When someone says 'it's only 103 today.'",
      "When the car seat buckle becomes a weapon.",
      "When the weather app says 'excessive heat warning' and you still have errands.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Arizona Script", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "group_chat_court",
    scriptTitle: "Who Wrote This Script?",
    scriptDescription: "The room questions the rule everyone acts like is normal.",
    socialScript: "There is a rule we are all supposed to follow.",
    scriptBreak: "Ask who wrote it, who benefits from it, and why we are still reading it.",
    audienceMirror: "Do you still follow this rule or did you break it already?",
    scriptCaptionStarter: "Who wrote this script, and why are we still reading it?",
    promptExamples: [
      "Who wrote the script that moms can't be overwhelmed?",
      "Who wrote the script that the oldest daughter has to fix everything?",
      "Who wrote the script that being quiet means being mature?",
      "Who wrote the script that women have to be nice to be respected?",
    ],
    scriptTags: ["Script Layer", "Script Break", "Mom Script", "Family Script"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "soft_pov",
    scriptTitle: "POV: The Script Stops Working",
    scriptDescription: "A quick POV moment where the old rule no longer fits the real feeling.",
    socialScript: "Keep performing the role even when it hurts.",
    scriptBreak: "Show the moment you realize the old script is not working anymore.",
    audienceMirror: "Have you reached this part yet?",
    scriptCaptionStarter: "POV: the old script stopped working.",
    promptExamples: [
      "POV: you realize being easy to love meant never needing anything.",
      "POV: you stop explaining yourself to someone committed to misunderstanding you.",
      "POV: you are done being the calm one in a room that keeps disrespecting you.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Soft Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "bts_real_process",
    scriptTitle: "Behind the Script",
    scriptDescription: "Show the real process behind creating the room: awkward starts, setup, retakes, comfort checks, laughs, and decisions.",
    socialScript: "Content should look effortless and perfect.",
    scriptBreak: "Show the real work behind the moment.",
    audienceMirror: "Do you like seeing the polished clip or the real process?",
    scriptCaptionStarter: "Behind the script: this is what it actually looked like.",
    promptExamples: [
      "Setting up before anyone acts normal.",
      "The laugh before the take.",
      "The moment someone says 'wait, what are we doing?'",
      "The real room before the final edit.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "az_tried_it",
    scriptTitle: "Arizona Hype Check",
    scriptDescription: "Try a local product, spot, or thing by comparing what people said it would be to the real room reaction.",
    socialScript: "The internet hype tells us what we are supposed to think.",
    scriptBreak: "The room tries it and reacts honestly.",
    audienceMirror: "Was Arizona right about this one?",
    scriptCaptionStarter: "Arizona hyped it up. The room tried it off script.",
    promptExamples: [
      "Everyone said this spot was worth the hype. Was it?",
      "Arizona said this was a must-try. The room has questions.",
      "The internet made this look cute. The room is trying it off script.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Arizona Script", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "friendship_energy",
    scriptTitle: "Friendship Script Check",
    scriptDescription: "Warm crew content that names the unspoken rules inside friendships.",
    socialScript: "Friendship means unlimited access, loyalty, and no boundaries.",
    scriptBreak: "Show the friend role people love, need, outgrow, or finally name.",
    audienceMirror: "Which friend are you, and which one do you need?",
    scriptCaptionStarter: "Every friend group has a script. Which one are you reading?",
    promptExamples: [
      "The friend who notices before you say anything.",
      "The friend who makes the plan and regrets it by Friday.",
      "The friend who tells the truth but brings snacks.",
      "The friend who goes quiet when something feels off.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Friendship Script"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "comment_to_clip",
    scriptTitle: "The Comments Broke the Script",
    scriptDescription: "Turn viewer comments into content by showing which script the comment is reading from.",
    socialScript: "Comments are just reactions to the surface.",
    scriptBreak: "The comment reveals the script the viewer is still reading.",
    audienceMirror: "Which comment are you — the one who broke it or the one still reading?",
    scriptCaptionStarter: "The comments broke the script. Here's what they really said.",
    promptExamples: [
      "Comment: 'You're so brave for saying that.' Script: brave means most people stay quiet.",
      "Comment: 'I could never do that.' Script: keeping the peace is safer than breaking it.",
      "Comment: 'That's just how family is.' Script: family is a free pass for disrespect.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Comment Reaction"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "search_explainer",
    scriptTitle: "What Is AZ Off Script?",
    scriptDescription: "A search-friendly explanation that defines the brand through broken social scripts, not just reactions.",
    socialScript: "A creator crew is just people posting together.",
    scriptBreak: "Define AZ Off Script as a room where people say what usually gets edited out.",
    audienceMirror: "Would you enter the room or just watch from the comments?",
    scriptCaptionStarter: "What is AZ Off Script? The short version: the script said be quiet. The room said otherwise.",
    promptExamples: [
      "AZ Off Script is where Arizona says the part people usually edit out.",
      "It is not a podcast. It is not random TikToks. It is the room breaking the script.",
      "Same prompt. Different women. Real reactions. No script needed.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "before_i_leave_house",
    scriptTitle: "Before Arizona Lets Me Leave",
    scriptDescription: "What Arizona requires before you leave the house, from heat survival to social readiness.",
    socialScript: "Leaving the house is simple.",
    scriptBreak: "Arizona adds extra rules.",
    audienceMirror: "What is on your Arizona leaving-the-house script?",
    scriptCaptionStarter: "Before I leave the house, Arizona needs me to run the checklist.",
    promptExamples: [
      "Water, sunglasses, backup patience, and parking shade strategy.",
      "Check the weather, then ignore it because it is still hot.",
      "Cute outfit until the steering wheel humbles you.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Arizona Script", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "kitchen_counter_confessions",
    scriptTitle: "Counter Truths",
    scriptDescription: "Easy home setup. One take. A truth said at the counter before it gets polished away.",
    socialScript: "The real thought stays in your kitchen, not online.",
    scriptBreak: "Say the kitchen-counter truth out loud.",
    audienceMirror: "What would you admit at the counter but not in the group chat?",
    scriptCaptionStarter: "Kitchen counter truth. No script, no audience voice.",
    promptExamples: [
      "I am tired of being called strong when nobody plans to help.",
      "Sometimes I miss who I was before I got tired.",
      "I do not want advice. I want somebody to admit this is hard.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Soft Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "which_one_are_you",
    scriptTitle: "Which Script Are You Reading?",
    scriptDescription: "Instead of just friend types, identify which role or script people fall into.",
    socialScript: "Everybody plays a role without naming it.",
    scriptBreak: "Name the role so people can see themselves.",
    audienceMirror: "Tag yourself, but be honest.",
    scriptCaptionStarter: "Which script are you reading? Tag yourself. Do not lie.",
    promptExamples: [
      "The over-explainer.",
      "The peacekeeper who is secretly exhausted.",
      "The quiet observer who already knows.",
      "The one who says 'I'm fine' and starts cleaning.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "arizona_which_one",
    scriptTitle: "Which Arizona Script Are You?",
    scriptDescription: "Arizona-specific roles that feel local, funny, and recognizable.",
    socialScript: "Everyone in Arizona handles Arizona the same way.",
    scriptBreak: "Show the different Arizona survival personalities.",
    audienceMirror: "Which Arizona version are you?",
    scriptCaptionStarter: "Which Arizona script are you reading today?",
    promptExamples: [
      "The shade hunter.",
      "The 'it's not that hot' liar.",
      "The iced drink person.",
      "The one who says west side like it is a personality.",
      "The one who refuses outdoor events after April.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Arizona Script", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "no_words_needed",
    scriptTitle: "Quiet Girl Script Break",
    scriptDescription: "Face reactions only. Perfect for quiet personalities because the reaction is the content.",
    socialScript: "If you are quiet, you have nothing to say.",
    scriptBreak: "Let the face carry the whole truth.",
    audienceMirror: "Quiet girls, did your face say this too?",
    scriptCaptionStarter: "Quiet girl version: no words, whole script broken.",
    promptExamples: [
      "When they say 'you're so quiet' but you heard everything.",
      "When the group finally realizes you were right.",
      "When somebody says the thing you decided not to say.",
    ],
    scriptTags: ["Script Layer", "Script Break", "No Talking Needed"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "off_script_looks",
    scriptTitle: "The Look Broke Script",
    scriptDescription: "Outfit, style, merch, or visual identity — but tied to what the look is saying without words.",
    socialScript: "Style is just how you look.",
    scriptBreak: "The look communicates the mood, role, boundary, or room energy.",
    audienceMirror: "What is your look saying before you say anything?",
    scriptCaptionStarter: "The outfit said what the script could not.",
    promptExamples: [
      "The 'I'm not explaining myself today' fit.",
      "The 'I came cute but I will still tell the truth' look.",
      "The 'quiet but clocking everything' outfit.",
      "The 'Arizona heat but make it intentional' fit.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "real_quick",
    scriptTitle: "Real Quick, Off Script",
    scriptDescription: "One honest thought that breaks a common rule, but keeps it quick.",
    socialScript: "If it is real, it has to be heavy or long.",
    scriptBreak: "Say the truth quickly before it gets over-explained.",
    audienceMirror: "Did that hit too fast?",
    scriptCaptionStarter: "Real quick. Off script.",
    promptExamples: [
      "Real quick, being tired does not make you ungrateful.",
      "Real quick, some people call you dramatic because the truth inconveniences them.",
      "Real quick, peace that only costs you is not peace.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Soft Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "fake_scenario_court",
    scriptTitle: "Fake Scenario, Real Script",
    scriptDescription: "Use fake situations to reveal real rules, expectations, and reactions without using anyone's real drama.",
    socialScript: "Fake scenarios are just for laughs.",
    scriptBreak: "The fake setup exposes a real social rule.",
    audienceMirror: "Why did this fake scenario feel too real?",
    scriptCaptionStarter: "Fake scenario. Real script exposed.",
    promptExamples: [
      "Your friend keeps inviting the person who embarrassed you. What script is she reading?",
      "He says he forgot your birthday but remembers game night. What now?",
      "Family says you changed because you stopped showing up for disrespect.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Friendship Script", "Dating Script"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "arizona_woman_math",
    scriptTitle: "Arizona Woman Logic",
    scriptDescription: "Funny Arizona logic, but framed as the rules women here use to survive the heat, plans, family, style, and errands.",
    socialScript: "Logic has to make sense to everyone.",
    scriptBreak: "Arizona logic makes sense if you live here.",
    audienceMirror: "Does this equation check out in Arizona?",
    scriptCaptionStarter: "Arizona woman logic. The math is emotional but accurate.",
    promptExamples: [
      "If the parking spot has shade, it is automatically closer.",
      "One iced drink equals one emotional support system.",
      "If the event is outdoors after May, the answer is maybe but emotionally no.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Arizona Script", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "what_she_really_means",
    scriptTitle: "The Line We're Not Reading",
    scriptDescription: "Translate the polite line into the real meaning underneath it.",
    socialScript: "The polite line is the full truth.",
    scriptBreak: "The room hears the hidden line underneath.",
    audienceMirror: "Did you hear the same thing she meant?",
    scriptCaptionStarter: "The line said one thing. The room heard another.",
    promptExamples: [
      "When she says 'it's fine,' the line we're not reading is...",
      "When she says 'do what you want,' the line we're not reading is...",
      "When she says 'I'm not mad,' the line we're not reading is...",
    ],
    scriptTags: ["Script Layer", "Script Break", "Polite Line"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "rank_it",
    scriptTitle: "Rank the Scripts",
    scriptDescription: "Rank which social rule, Arizona problem, or group habit is most exhausting, funny, or true.",
    socialScript: "All annoyances are equal.",
    scriptBreak: "The room ranks what actually drains or triggers people.",
    audienceMirror: "What would you rank first?",
    scriptCaptionStarter: "The room ranked the scripts. Which one is number one for you?",
    promptExamples: [
      "Rank these: be the bigger person, keep the peace, don't take it personal, that's just family.",
      "Rank Arizona problems: car heat, outdoor plans, dust, traffic, people saying it's a dry heat.",
      "Rank friendship scripts: always available, always supportive, never honest, never changing.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Funny Truth"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "room_temperature_check",
    scriptTitle: "Room Temperature Check",
    scriptDescription: "Not weather — vibe. Check whether the room is still reading the script or ready to break it.",
    socialScript: "Everybody is fine because nobody said otherwise.",
    scriptBreak: "Read the actual room temperature before the polite script takes over.",
    audienceMirror: "What is the real temperature in your room?",
    scriptCaptionStarter: "Room temperature check: are we reading the script or breaking it?",
    promptExamples: [
      "Room temperature check: everybody says they're fine, but are they?",
      "Room temperature check: is this petty, honest, or overdue?",
      "Room temperature check: are we laughing or uncomfortable because it is true?",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "dont_overthink_it",
    scriptTitle: "Don't Let the Script Answer",
    scriptDescription: "One prompt, answer fast. First answer wins before the polite script takes over.",
    socialScript: "Filter the answer until it sounds acceptable.",
    scriptBreak: "Answer before you edit yourself.",
    audienceMirror: "Was your first answer the real one?",
    scriptCaptionStarter: "Don't overthink it. Don't let the script answer.",
    promptExamples: [
      "Forgive or distance?",
      "Text back or leave it?",
      "Family or boundary?",
      "Explain or disappear?",
      "Keep peace or tell truth?",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "two_second_opinion",
    scriptTitle: "Two-Second Script Break",
    scriptDescription: "Yes or no, fast. The point is to catch the instinct before the explanation.",
    socialScript: "Every answer needs a long explanation to be valid.",
    scriptBreak: "Let the instinct answer first.",
    audienceMirror: "Did your instinct match the room?",
    scriptCaptionStarter: "Two seconds. No script. What's your answer?",
    promptExamples: [
      "Would you go back?",
      "Is that disrespect?",
      "Is silence an answer?",
      "Would you invite her?",
      "Would you apologize first?",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "different_women_different_answer",
    scriptTitle: "Same Script, Different Woman",
    scriptDescription: "Each woman responds to the same invisible rule from her own personality, experience, and timing.",
    socialScript: "The same situation should produce the same answer.",
    scriptBreak: "The same script lands differently depending on who is reading it.",
    audienceMirror: "Which woman read it like you?",
    scriptCaptionStarter: "Same script. Different women. Nobody read it the same.",
    promptExamples: [
      "Script: Don't make it awkward.",
      "Script: Just forgive them.",
      "Script: Don't be dramatic.",
      "Script: Be grateful.",
      "Script: That's just how family is.",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "first_wave_vs_future",
    scriptTitle: "First Wave, New Scripts",
    scriptDescription: "First Wave reacts to the kind of energy, boundaries, humor, and honesty future members should bring.",
    socialScript: "New people should fit in by copying the room.",
    scriptBreak: "Future waves can bring new scripts, not just repeat the first one.",
    audienceMirror: "What kind of energy should enter the room next?",
    scriptCaptionStarter: "The room is growing. New women, new scripts, same Off Script energy.",
    promptExamples: [
      "What kind of woman belongs in the next wave?",
      "What energy should walk into the room next?",
      "What script should future members already be done reading?",
      "What should never enter the room?",
    ],
    scriptTags: ["Script Layer", "Script Break"],
    depthLevel: "light / funny / honest depending on prompt",
  },
  {
    templateId: "black_latina_lens",
    scriptTitle: "Culture Script Check",
    scriptDescription: "Cultural takes that name real family, community, auntie, tía, womanhood, and respectability scripts without making culture the whole brand.",
    socialScript: "Culture means you have to accept certain rules without questioning them.",
    scriptBreak: "Name the cultural script, honor the truth, and question what no longer fits.",
    audienceMirror: "Were you taught this too, or did your house have a different script?",
    scriptCaptionStarter: "Culture script check: who taught us this one?",
    promptExamples: [
      "The auntie would say keep it in the family. The room has questions.",
      "The script said don't talk back. The adult version says speak clearly.",
      "Respect is not silence.",
      "Family love and family pressure are not the same thing.",
    ],
    scriptTags: ["Script Layer", "Script Break", "Culture Script", "Family Script"],
    depthLevel: "light / funny / honest depending on prompt",
  },
];

/** Lookup map: templateId -> OffScriptVersion */
export const OFF_SCRIPT_BY_TEMPLATE_ID = new Map<string, OffScriptVersion>(
  OFF_SCRIPT_VERSIONS.map((v) => [v.templateId, v])
);
