/**
 * Profile Dropdown Options — pre-made choices for crew profile fields.
 *
 * Members pick from these lists instead of typing in blanks. Every list
 * includes an "Other" option so they can write their own if nothing fits.
 * Several lists also include "Not sure yet" /
 * "I need help choosing" so members don't have to decide alone.
 *
 * Splits into two groups:
 *  - PORTAL_OPTIONS: shown inside the portal only, saves instantly, no approval
 *  - PUBLIC_OPTIONS: shown on the public website, goes to admin for approval
 */

// ===== PORTAL-ONLY (saves instantly, no approval) =====

export const NICKNAME_TITLE_OPTIONS = [
  "The Real One",
  "The Sweet Touch",
  "The Quiet Surprise",
  "The Wild Card",
  "The Fresh Energy",
  "The Room Builder",
  "The Side-Eye Specialist",
  "The Calm Chaos",
  "The Soft Truth",
  "The Funny One",
  "The Honest One",
  "The Peacekeeper",
  "The Plot Twist",
  "The Reaction Queen",
  "The Vibe Check",
  "The Face Card",
  "The Lowkey One",
  "The Loud Laugh",
  "The Gentle Chaos",
  "The Smooth Talker",
  "The Unbothered One",
  "The Question Asker",
  "The Friend Who Notices Everything",
  "The One Who Says It",
  "The One Who Knows Better",
  "The Arizona Energy",
  "Other",
] as const;

export const AVAILABILITY_OPTIONS = [
  "Weekday mornings",
  "Weekday afternoons",
  "Weekdays after 5 PM",
  "Friday evenings",
  "Saturday mornings",
  "Saturday afternoons",
  "Saturday evenings",
  "Sunday mornings",
  "Sunday afternoons",
  "Sunday evenings",
  "Once a week",
  "Twice a month",
  "Once a month",
  "Flexible with notice",
  "Depends on childcare",
  "Depends on transportation",
  "Other",
] as const;

export const ROOM_VIBE_OPTIONS = [
  "Funny",
  "Quiet",
  "Blunt",
  "Warm",
  "Polished",
  "Chaotic",
  "Calm",
  "Stylish",
  "Thoughtful",
  "Unexpected",
  "Soft-spoken",
  "Expressive",
  "Animated",
  "Dry humor",
  "Sarcastic",
  "Sweet",
  "Bold",
  "Unbothered",
  "Dramatic in a funny way",
  "Natural storyteller",
  "Quick with comebacks",
  "Good listener",
  "Good facial reactions",
  "Side-eye energy",
  "Peacekeeper",
  "Pot stirrer",
  "Mama energy",
  "Auntie energy",
  "Big sister energy",
  "Little sister energy",
  "Soft truth energy",
  "Hot take energy",
  "Group chat energy",
  "Arizona energy",
  "Lowkey",
  "High energy",
  "Observant",
  "Honest",
  "Playful",
  "Confident",
  "Reserved",
  "Curious",
  "Messy in a funny way",
  "Grounded",
  "Still figuring it out",
  "Other",
] as const;

export const ONE_LINER_OPTIONS = [
  "My face usually says it first.",
  "I'm quiet until I'm not.",
  "I bring the soft truth.",
  "I say what everyone else was thinking.",
  "I'm calm, but I heard everything.",
  "I keep it cute until the prompt gets messy.",
  "I'm the side-eye before the answer.",
  "I'm the one who asks the question.",
  "I'm funny without trying.",
  "I'm the unexpected answer.",
  "I bring warm energy.",
  "I bring real reactions.",
  "I bring the plot twist.",
  "I'm still figuring out my vibe.",
  "Other",
] as const;

export const CAMERA_COMFORT_OPTIONS = [
  "Comfortable on camera",
  "Comfortable after warming up",
  "Better in group videos",
  "Better filming alone",
  "Better with prompts",
  "Better with facial reactions",
  "Better with no-talking clips",
  "Better behind the camera",
  "Nervous but willing to try",
  "Not comfortable right now",
  "Ask me each time",
] as const;

export const CONTENT_COMFORT_OPTIONS = [
  "Open to most prompts",
  "Light and funny only",
  "Soft truths are okay",
  "Hot takes are okay",
  "Messy topics are okay if respectful",
  "Group games only",
  "Reaction clips only",
  "No personal stories",
  "No relationship topics",
  "No family topics",
  "No kids",
  "Ask me first depending on the prompt",
] as const;

export const DO_NOT_USE_FOR_OPTIONS = [
  "My kids on camera",
  "My home/location shown",
  "My job/workplace mentioned",
  "My relationship discussed",
  "Dating topics",
  "Marriage topics",
  "Sexual topics",
  "Religion topics",
  "Politics",
  "Money/finances",
  "Weight/body comments",
  "Mental health topics",
  "Family drama",
  "Specific people being named",
  "Messy personal stories",
  "Embarrassing clips",
  "Bad angles",
  "No-makeup closeups",
  "Crying/emotional moments",
  "Arguments/conflict",
  "Anything that makes me look mean",
  "Anything that could affect my job",
  "Anything involving alcohol",
  "Anything involving smoking/vaping",
  "Anything with strong language",
  "Anything unsafe or too location-specific",
  "Ask me first depending on the clip",
] as const;

export const TAG_ME_OPTIONS = [
  "Yes, tag me when I'm posted",
  "Ask me before tagging",
  "Only tag me on certain clips",
  "Post me but don't tag me",
  "Do not tag me publicly",
  "I do not have a public handle yet",
] as const;

export const BEST_PLATFORM_OPTIONS = [
  "TikTok",
  "Instagram",
  "Facebook",
  "YouTube",
  "Threads",
  "No public handle",
  "Ask me before tagging",
] as const;

// ===== PUBLIC WEBSITE (needs admin approval before going live) =====

export const PUBLIC_TITLE_OPTIONS = [
  "The Room Builder",
  "The Real One",
  "The Sweet Touch",
  "The Quiet Surprise",
  "The Wild Card",
  "The Fresh Energy",
  "The Side-Eye Specialist",
  "The Calm Chaos",
  "The Soft Truth",
  "The Honest One",
  "The Funny One",
  "The Vibe Check",
  "The Plot Twist",
  "The Reaction Queen",
  "The Lowkey One",
  "The Loud Laugh",
  "The Peacekeeper",
  "The Gentle Chaos",
  "The Unbothered One",
  "The Face Says It First",
  "The Friend Who Notices Everything",
  "The One Who Says It",
  "The One With the Look",
  "The Quiet Fire",
  "The Smooth Energy",
  "The Sharp One",
  "The Warm One",
  "The Bold One",
  "The Soft-Spoken One",
  "The \u201cI Said What I Said\u201d One",
  "The Arizona Energy",
  "The Group Chat Witness",
  "The Red Flag Reader",
  "The Real-Life Defender",
  "The Soft Truth Teller",
  "The Chaos Translator",
  "The Calm But Correct One",
  "Other",
] as const;

export const SECONDARY_ROLE_OPTIONS = [
  "Founder + Creative Lead",
  "First Wave Creator",
  "First Wave Creator + Calendar Planner",
  "Calendar Planner",
  "Creative Planner",
  "Room Participant",
  "Round 2 Creator",
  "Featured Face",
  "Guest Face",
  "Reaction Dropper",
  "Group Game Creator",
  "Hot Take Creator",
  "AZ Moments Creator",
  "Trend Drop Creator",
  "Mom-Life Creator",
  "Comedy Skit Creator",
  "Behind-the-Scenes Support",
  "Content Ideas Contributor",
  "Filming Support",
  "Editing Support",
  "Brand Support",
  "Not public",
  "Other",
] as const;

export const PERSONALITY_LINE_OPTIONS = [
  "Says what everyone else was thinking.",
  "The reaction might say more than the answer.",
  "Brings the warm energy and the funny timing.",
  "You never know where the answer is going.",
  "Makes a simple question turn into a whole moment.",
  "Quiet until the face says everything.",
  "Soft voice, strong opinion.",
  "Calm energy, dangerous side-eye.",
  "The one who notices everything.",
  "The one who asks the question everyone avoided.",
  "Funny without trying too hard.",
  "Brings the plot twist.",
  "Keeps it cute until the prompt gets messy.",
  "Reads the room and still says it.",
  "Turns a reaction into the whole clip.",
  "Makes the group debate harder than it needed to.",
  "The answer may be quiet, but the face is loud.",
  "Sweet until the hot take comes out.",
  "Warm, honest, and easy to watch.",
  "Not loud, just accurate.",
  "The pause says enough.",
  "The group chat needed this one.",
  "The face broke the script first.",
  "Says the soft truth out loud.",
  "The calm one with the real answer.",
  "The one who makes everyone react.",
  "Other",
] as const;

export const WEBSITE_BIO_OPTIONS = [
  "A real-reaction creator in the AZ Off Script room, bringing natural timing, honest answers, and the kind of energy that makes a simple prompt turn into a moment.",
  "A First Wave creator with a mix of humor, real reactions, and off-script honesty. She brings her own rhythm to the room and helps make the group chemistry feel real.",
  "A calm but expressive voice in the room, bringing side-eye, soft truths, and reactions that say what words do not always need to.",
  "A funny, natural presence in the AZ Off Script room, bringing quick reactions, honest timing, and the kind of personality people recognize in their own group chat.",
  "A bold voice in the room, bringing hot takes, real answers, and the kind of reactions that make people choose a side in the comments.",
  "A warm and creative part of AZ Off Script, bringing personality, timing, and a little extra flavor to the room.",
  "A fresh face in the AZ Off Script room, bringing her own perspective, real reactions, and energy that helps every prompt feel different.",
  "A quiet but memorable presence, proving that the best reaction is not always the loudest one.",
  "A natural fit for group games, reaction clips, and the kind of off-script moments that happen when nobody is trying too hard.",
  "A creator in the AZ Off Script room who brings humor, honesty, and the kind of face that says everything before the answer does.",
  "Other",
] as const;

/**
 * Helper — returns true if a value matches one of the preset options.
 * Used to decide whether to show "Other" input or keep the dropdown selection.
 */
export function isPresetOption(value: string | null | undefined, options: readonly string[]): boolean {
  if (!value) return false;
  return options.includes(value as any);
}
